apiVersion: tekton.dev/v1beta1 
kind: Task 
metadata: 
  name: build-and-push-image 
spec:
  params:
    - name: image-name 
      type: string 
      description: The name of the image to build and push 
    - name: image-tag
      type: string 
      description: The tag for the image (e.g., latest, v1.0). 
      default: "latest"
    - name: dockerfile-path 
      type: string 
      default: "gs-spring-boot/complete"  
  workspaces:
    - name: source 
      description: The workspace containing the source code and Dockerfile. 
    - name: docker-config 
      description: The workspace for Docker credentials 
  steps: 
    - name: build-and-push 
      image: gcr.io/kaniko-project/executor:latest 
      env:
        - name: DOCKERFILE_PATH 
          value: Dockerfile 
      args:
        #- --dockerfile=$(workspaces.source.path)/$(params.dockerfile-path)/$(env.DOCKERFILE_PATH)
        - --dockerfile=$(workspaces.source.path)/$(params.dockerfile-path)/Dockerfile
        - --context=dir://$(workspaces.source.path)/$(params.dockerfile-path)
        - --destination=$(params.image-name):$(params.image-tag)
        - --insecure=true 
  #     volumeMounts:  
  #       - name: docker-config 
  #         mountPath: /kaniko/.docker/config.json
  #         subPath: .dockerconfigjson 
  #         readOnly: true 
  # volumes:
  #   - name: docker-config 
  #     secret: 
  #       secretName: regcred 
